"""
Django settings for md_edit project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from decouple import config

from md_edit.config import *

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG')

if DEBUG:
    MIDDLEWARE += ('django-debug-helper.debug.ErrorSearchMiddleware',)

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

ROOT_URLCONF = 'md_edit.urls'

WSGI_APPLICATION = 'md_edit.wsgi.application'
